# Generated by Django 5.1.3 on 2024-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('direction', models.CharField(choices=[('ACROSS', '横のカギ'), ('DOWN', '縦のカギ')], max_length=6)),
                ('clue', models.TextField()),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
