# Generated by Django 5.1.3 on 2024-11-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcrossClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DownClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Clue',
        ),
    ]
